In [1]:
import pandas
import numpy
import sklearn.feature_selection 
from pandas import read_csv
from pandas import set_option
from numpy import set_printoptions
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2


data = pandas.read_csv('./US_Accidents_March23.csv')
data2 = pandas.read_csv('./train_mobile.csv')

In [2]:
set_option('display.width', 100)
correlations = data.corr(method='pearson', numeric_only=True)
print(correlations)

                   Severity  Start_Lat  Start_Lng  End_Lat  End_Lng  Distance(mi)  Temperature(F)  \
Severity           1.000000  -0.076981  -0.103261      NaN      NaN      0.034340        0.046538   
Start_Lat         -0.076981   1.000000   0.861073      NaN      NaN      0.103625       -0.567659   
Start_Lng         -0.103261   0.861073   1.000000      NaN      NaN      0.120892       -0.748900   
End_Lat                 NaN        NaN        NaN      NaN      NaN           NaN             NaN   
End_Lng                 NaN        NaN        NaN      NaN      NaN           NaN             NaN   
Distance(mi)       0.034340   0.103625   0.120892      NaN      NaN      1.000000       -0.109664   
Temperature(F)     0.046538  -0.567659  -0.748900      NaN      NaN     -0.109664        1.000000   
Wind_Chill(F)     -0.227485  -0.193373  -0.181182      NaN      NaN     -0.017924        0.977217   
Humidity(%)       -0.051149   0.265370   0.468385      NaN      NaN      0.080519       -0.

In [3]:
# dalla matrice di correlazione vediamo che sono correlate:
#        Start_Lat e Start_Lng (0.86 ca)
#        Start_Lng e Temperature (-0.74 ca)
#        Wind_Chill e Temperature (0.97 ca)
#        Humidity e Temperature (-0.87 ca)

In [4]:
# metodi di scelta delle feature del dataset train_mobile con price range scelta come variabile da predirre (output)

In [5]:
# uso Univariate Selection, un test statistico per selezionare le feature che incidono 
# maggiormente sulla variabile in output

array2 = data2.values
X2 = array2[:,0:20]
Y2 = array2[:,20]

# estrazione features
test2 = SelectKBest(score_func=chi2, k=4)
fit2 = test2.fit(X2,Y2)

# riassunto punteggi
print(fit2.scores_)
features2 = fit2.transform(X2)

# riassunto features selezionate
print(features2[0:5,:])

[1.41298666e+04 7.23232323e-01 6.48365906e-01 6.31010795e-01
 1.01351665e+01 1.52157239e+00 8.98391244e+01 7.45819631e-01
 9.59728626e+01 9.09755558e+00 9.18605355e+00 1.73635695e+04
 9.81058675e+03 9.31267519e+05 9.61487832e+00 1.64803191e+01
 1.32364000e+01 3.27642810e-01 1.92842942e+00 4.22090730e-01]
[[ 842.   20.  756. 2549.]
 [1021.  905. 1988. 2631.]
 [ 563. 1263. 1716. 2603.]
 [ 615. 1216. 1786. 2769.]
 [1821. 1208. 1212. 1411.]]


In [6]:
# le features che incidono maggiormente sul price range sono in ordine: 
#        ram (9.31267519e+05)
#        px_height (1.73635695e+04)
#        px_width (9.81058675e+03)
#        battery_power (1.41298666e+04)
# la matrice sotto indica i valori in input delle features selezionate (abbiamo preso le prime 5 righe 
# per avere un output più leggibile)

In [7]:
# prova con il dataset sugli incidenti stradali

print(data)

          ID   Source  Severity           Start_Time             End_Time  Start_Lat   Start_Lng  \
0        A-1  Source2         3  2016-02-08 05:46:00  2016-02-08 11:00:00  39.865147  -84.058723   
1        A-2  Source2         2  2016-02-08 06:07:59  2016-02-08 06:37:59  39.928059  -82.831184   
2        A-3  Source2         2  2016-02-08 06:49:27  2016-02-08 07:19:27  39.063148  -84.032608   
3        A-4  Source2         3  2016-02-08 07:23:34  2016-02-08 07:53:34  39.747753  -84.205582   
4        A-5  Source2         2  2016-02-08 07:39:07  2016-02-08 08:09:07  39.627781  -84.188354   
...      ...      ...       ...                  ...                  ...        ...         ...   
2831  A-2832  Source2         2  2016-07-12 15:12:42  2016-07-12 16:27:42  38.474407 -121.419067   
2832  A-2833  Source2         2  2016-07-12 15:45:38  2016-07-12 17:00:38  38.495541 -121.511070   
2833  A-2834  Source2         3  2016-07-12 15:26:19  2016-07-12 16:41:19  38.588917 -121.415375   


In [8]:


categorical_columns = data.select_dtypes(exclude='number').columns.tolist()
data = data.drop(columns = categorical_columns)
array = data.values

X = array[:,1:12]
Y = array[:,0]

print(data)
# estrazione features
test = SelectKBest(score_func=chi2, k=4)
fit = test.fit(X,Y)

# riassunto punteggi
print(fit.scores_)
features = fit.transform(X)

# riassunto features selezionate
print(features[0:5,:])

      Severity  Start_Lat   Start_Lng  End_Lat  End_Lng  Distance(mi)  Temperature(F)  \
0            3  39.865147  -84.058723      NaN      NaN          0.01            36.9   
1            2  39.928059  -82.831184      NaN      NaN          0.01            37.9   
2            2  39.063148  -84.032608      NaN      NaN          0.01            36.0   
3            3  39.747753  -84.205582      NaN      NaN          0.01            35.1   
4            2  39.627781  -84.188354      NaN      NaN          0.01            36.0   
...        ...        ...         ...      ...      ...           ...             ...   
2831         2  38.474407 -121.419067      NaN      NaN          0.00            87.1   
2832         2  38.495541 -121.511070      NaN      NaN          0.00            88.0   
2833         3  38.588917 -121.415375      NaN      NaN          0.00            89.6   
2834         2  38.742481 -120.747398      NaN      NaN          0.00            84.2   
2835         2  38.56

ValueError: Input X contains NaN.
SelectKBest does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

In [ ]:
#import sklearn.linear_model
#from sklearn.feature_selection import RFE
#from sklearn.linear_model import LogisticRegression
# load data


#array = data2.values
#X = array[:,0:20]
#Y = array[:,20]
# feature extraction
#model = LogisticRegression()
#rfe = RFE(model, 3)
#fit = rfe.fit(X, Y)
#print("Num Features: %d") % fit.n_features_
#print("Selected Features: %s") % fit.support_
#print("Feature Ranking: %s") % fit.ranking_